site_name: DATAIDEA
site_url: https://web.dataidea.org/
site_author: Juma Shafara
site_description: DATAIDEA SCIENCE - Learn Programming for Data Science 

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true

theme:
  name: material
  palette:
    # Dark grayscale theme only
    - scheme: slate
      primary: grey
      accent: grey
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  custom_dir: docs/overrides

extra_css:
  - stylesheets/grayscale.css

nav:
  - Home: index.md
  - HTML:
    - HTML/01_introduction.md
    - HTML/02_basic_structure.md
    - HTML/03_text_formatting.md
    - HTML/04_links_and_images.md
    - HTML/05_lists_and_tables.md
    - HTML/06_forms.md
  - CSS:
    - CSS/01_introduction.md
    - CSS/02_syntax_and_selectors.md
    - CSS/03_colors_text_fonts.md
    - CSS/04_box_model_layout.md
    - CSS/05_flexbox.md
    - CSS/06_responsive_design.md
  - JavaScript:
    - JavaScript/01_introduction.md
    - JavaScript/02_variables_data_types.md
    - JavaScript/03_functions_scope.md
    - JavaScript/04_control_flow.md
    - JavaScript/05_dom_manipulation.md
    - JavaScript/06_events.md
  - Git:
    - Git/01_introduction.md
    - Git/02_basic_commands.md
    - Git/03_branching.md
    - Git/04_github.md
    - Git/05_collaboration.md
    - Git/06_advanced.md
  - SQL:
    - SQL/01_introduction.md
    - SQL/02_basic_queries.md
    - SQL/03_filtering.md
    - SQL/04_aggregate_functions.md
    - SQL/05_joins.md
    - SQL/06_subqueries.md
  - Python:
    - Python/index.md
    - Python/11_python_tutorial.ipynb
    - Basics:
      - Python/Basics/00_python_programming_outline.ipynb
      - Python/Basics/01_basics.ipynb
      - Python/Basics/02_variables.ipynb
      - Python/Basics/03_numbers.ipynb
      - Python/Basics/03_strings.ipynb
      - Python/Basics/04_operators.ipynb
      - Python/Basics/05_containers.ipynb
      - Python/Basics/06_flow_control.ipynb
      - Python/Basics/07_advanced.ipynb
      - Python/Basics/08_modules.ipynb
      - Python/Basics/09_file_handling.ipynb
      - Python/Basics/13_end_of_course_exercise.ipynb
    - Exercises:
      - Python/Exercises/02_basics_exercise.ipynb
      - Python/Exercises/11_python_objective_quiz.ipynb
      - Python/Exercises/12_true_or_false_quiz.ipynb
      - Python/Exercises/13_end_of_course_exercise.ipynb
    - Python Builtin:
      - Python/Python Builtin/filter_function.md
      - Python/Python Builtin/map_function.md
      - Python/Python Builtin/reduce_function.md
  - Django:
    - Django/01_introduction.md
    - Django/02_setup.md
    - Django/03_models_databases.md
    - Django/04_views_urls.md
    - Django/05_templates.md
    - Django/06_forms.md
